<?xml version="1.0" encoding="UTF-8"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title></title>
            </titleStmt>
            <publicationStmt>
                <publisher>University of Bristol</publisher>
            </publicationStmt>
            <sourceDesc>
                <msDesc>
                    <msIdentifier>
                        <country>United Kingdom</country>
                        <settlement>London</settlement>
                        <repository>The National Archives</repository>
                        <collection>Subseries within E 101. Irish Excheqer Accounts.</collection>
                    </msIdentifier>
                </msDesc>
            </sourceDesc>
        </fileDesc>
    </teiHeader>
    <text type="roll>